[package]
name = "bukno-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bukno-core.workspace = true
tokio = { workspace = true, features = ["macros"] }
uuid = { version = "1.26", features = ["v4"] }

[lints]
workspace = true
