//! Reads the canonical design tokens at build time and generates one typed
//! `Tokens` value. The build fails when a required token is missing or
//! malformed, so the app can never ship with a silently invented value.

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::PathBuf;

use serde_json::Value;

const COLORS: &[&str] = &[
    "surface-sidebar",
    "surface-panel",
    "surface-canvas",
    "surface-code",
    "surface-hover",
    "surface-selected",
    "surface-composer",
    "surface-raised",
    "surface-popover",
    "divider",
    "text-primary",
    "text-secondary",
    "text-tertiary",
    "text-disabled",
    "codex",
    "codex-tint",
    "codex-effort-1",
    "codex-effort-2",
    "codex-effort-3",
    "codex-effort-4",
    "codex-effort-5",
    "claude",
    "claude-tint",
    "claude-effort-1",
    "claude-effort-2",
    "claude-effort-3",
    "claude-effort-4",
    "claude-effort-5",
    "positive",
    "negative",
    "attention",
    "on-attention",
    "action",
    "on-action",
    "focus",
    "scrim",
];
const TYPE_STYLES: &[&str] = &[
    "t-display",
    "t-title",
    "t-heading",
    "t-body",
    "t-ui",
    "t-ui-strong",
    "t-small",
    "t-caption",
    "t-code",
    "t-mono-small",
];
const SPACING: &[&str] =
    &["space-1", "space-2", "space-3", "space-4", "space-5", "space-6", "space-8", "space-10", "space-12"];
const RADII: &[&str] =
    &["radius-xs", "radius-sm", "radius-md", "radius-lg", "radius-bubble", "radius-xl", "radius-full"];
const SHADOWS: &[&str] = &["shadow-raised", "shadow-composer", "shadow-popover", "focus-ring"];
const SIZES: &[&str] = &[
    "size-titlebar",
    "size-sidebar",
    "size-panel",
    "size-column",
    "size-row",
    "size-control",
    "size-control-sm",
    "size-composer-min",
    "size-inset-bottom",
    "size-avatar",
];
const DURATIONS: &[&str] = &[
    "dur-press",
    "dur-quick",
    "dur-standard",
    "dur-settle",
    "dur-crossfade",
    "loop-working",
    "loop-breathe",
    "loop-shimmer",
];
const EASINGS: &[&str] = &["ease-standard", "ease-exit"];

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let path = manifest.join("../../docs/design/system/tokens.json");
    println!("cargo:rerun-if-changed={}", path.display());
    let source =
        std::fs::read_to_string(&path).unwrap_or_else(|e| fail(&format!("cannot read {}: {e}", path.display())));
    let json: Value =
        serde_json::from_str(&source).unwrap_or_else(|e| fail(&format!("tokens.json is not valid JSON: {e}")));

    let mut out = String::from("// Generated by build.rs from docs/design/system/tokens.json. Do not edit.\n\n");

    // Colours, with {references} resolved.
    let raw = named_values(&json, "color");
    let mut colors = Vec::new();
    for name in COLORS {
        let value = resolve(&raw, name, 0);
        colors.push((name, parse_hex(name, &value)));
    }
    struct_def(&mut out, "Colors", COLORS, "Color32");
    out.push_str("pub fn colors() -> Colors {\n    Colors {\n");
    for (name, [r, g, b, a]) in &colors {
        writeln!(out, "        {}: Color32::from_rgba_unmultiplied({r}, {g}, {b}, {a}),", field(name)).unwrap();
    }
    out.push_str("    }\n}\n\n");

    // Type styles.
    let groups = json["type"]["groups"].as_array().unwrap_or_else(|| fail("type.groups is missing"));
    let mut styles: HashMap<String, (Value, bool)> = HashMap::new();
    for group in groups {
        let mono = group["family"].as_str() == Some("mono");
        for style in group["styles"].as_array().into_iter().flatten() {
            if let Some(name) = style["name"].as_str() {
                styles.insert(name.to_owned(), (style.clone(), mono));
            }
        }
    }
    struct_def(&mut out, "TypeStyles", TYPE_STYLES, "TypeStyle");
    out.push_str("pub fn type_styles() -> TypeStyles {\n    TypeStyles {\n");
    for name in TYPE_STYLES {
        let (style, mono) = styles.get(*name).unwrap_or_else(|| missing("type", name));
        let size = px(name, style["fontSize"].as_str().unwrap_or_else(|| missing("fontSize of", name)));
        let line = px(name, style["lineHeight"].as_str().unwrap_or_else(|| missing("lineHeight of", name)));
        let weight = style["fontWeight"].as_u64().unwrap_or_else(|| missing("fontWeight of", name));
        if ![400, 500, 600].contains(&weight) {
            fail(&format!("{name} uses weight {weight}; the bundled fonts cover 400, 500 and 600"));
        }
        let spacing = match style["letterSpacing"].as_str() {
            None => 0.0,
            Some(em) => {
                let v: f32 = em
                    .trim_end_matches("em")
                    .parse()
                    .unwrap_or_else(|_| fail(&format!("bad letterSpacing for {name}")));
                v * size
            }
        };
        writeln!(
            out,
            "        {}: TypeStyle {{ size: {size:?}, line_height: {line:?}, weight: {weight}, letter_spacing: {spacing:?}, mono: {mono} }},",
            field(name)
        )
        .unwrap();
    }
    out.push_str("    }\n}\n\n");

    // Plain length groups.
    for (group, names, ty) in [("spacing", SPACING, "Spacing"), ("radius", RADII, "Radii"), ("size", SIZES, "Sizes")] {
        let raw = named_values(&json, group);
        struct_def(&mut out, ty, names, "f32");
        writeln!(out, "pub fn {group}() -> {ty} {{\n    {ty} {{").unwrap();
        for name in names {
            let value = raw.get(*name).unwrap_or_else(|| missing(group, name));
            writeln!(out, "        {}: {:?},", field(name), px(name, value)).unwrap();
        }
        out.push_str("    }\n}\n\n");
    }

    // Durations, in seconds.
    let raw = named_values(&json, "duration");
    struct_def(&mut out, "Durations", DURATIONS, "f32");
    out.push_str("pub fn durations() -> Durations {\n    Durations {\n");
    for name in DURATIONS {
        let value = raw.get(*name).unwrap_or_else(|| missing("duration", name));
        let ms: f32 = value
            .strip_suffix("ms")
            .and_then(|v| v.parse().ok())
            .unwrap_or_else(|| fail(&format!("{name} must be in ms, found {value}")));
        writeln!(out, "        {}: {:?},", field(name), ms / 1000.0).unwrap();
    }
    out.push_str("    }\n}\n\n");

    // Easing curves.
    let raw = named_values(&json, "easing");
    struct_def(&mut out, "Easings", EASINGS, "[f32; 4]");
    out.push_str("pub fn easings() -> Easings {\n    Easings {\n");
    for name in EASINGS {
        let value = raw.get(*name).unwrap_or_else(|| missing("easing", name));
        let inner = value
            .strip_prefix("cubic-bezier(")
            .and_then(|v| v.strip_suffix(')'))
            .unwrap_or_else(|| fail(&format!("{name} must be a cubic-bezier, found {value}")));
        let n: Vec<f32> = inner.split(',').map(|p| p.trim().parse().unwrap()).collect();
        if n.len() != 4 {
            fail(&format!("{name} needs four control values"));
        }
        writeln!(out, "        {}: [{:?}, {:?}, {:?}, {:?}],", field(name), n[0], n[1], n[2], n[3]).unwrap();
    }
    out.push_str("    }\n}\n\n");

    // Shadows as layers.
    let raw = named_values(&json, "shadow");
    struct_def(&mut out, "Shadows", SHADOWS, "Vec<ShadowLayer>");
    out.push_str("pub fn shadows() -> Shadows {\n    Shadows {\n");
    for name in SHADOWS {
        let value = raw.get(*name).unwrap_or_else(|| missing("shadow", name));
        writeln!(out, "        {}: vec![", field(name)).unwrap();
        for layer in value.split(", ") {
            let mut parts: Vec<&str> = layer.split_whitespace().collect();
            let inset = parts.first() == Some(&"inset");
            if inset {
                parts.remove(0);
            }
            let color = parts.pop().unwrap_or_else(|| fail(&format!("{name}: empty layer")));
            let [r, g, b, a] = parse_hex(name, color);
            let lengths: Vec<f32> = parts.iter().map(|p| px(name, p)).collect();
            if !(2..=4).contains(&lengths.len()) {
                fail(&format!("{name}: expected 2 to 4 lengths in {layer:?}"));
            }
            let get = |i: usize| lengths.get(i).copied().unwrap_or(0.0);
            writeln!(
                out,
                "            ShadowLayer {{ inset: {inset}, x: {:?}, y: {:?}, blur: {:?}, spread: {:?}, color: Color32::from_rgba_unmultiplied({r}, {g}, {b}, {a}) }},",
                get(0), get(1), get(2), get(3)
            )
            .unwrap();
        }
        out.push_str("        ],\n");
    }
    out.push_str("    }\n}\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("tokens.rs");
    std::fs::write(dest, out).unwrap();
}

fn fail(message: &str) -> ! {
    panic!("design tokens: {message}");
}

fn missing(group: &str, name: &str) -> ! {
    fail(&format!("required token {name} is missing from {group} in tokens.json"))
}

fn named_values(json: &Value, group: &str) -> HashMap<String, String> {
    json[group]["tokens"]
        .as_array()
        .unwrap_or_else(|| fail(&format!("{group}.tokens is missing")))
        .iter()
        .filter_map(|t| Some((t["name"].as_str()?.to_owned(), t["value"].as_str()?.to_owned())))
        .collect()
}

fn resolve(raw: &HashMap<String, String>, name: &str, depth: usize) -> String {
    if depth > 8 {
        fail(&format!("reference cycle at {name}"));
    }
    let value = raw.get(name).unwrap_or_else(|| missing("color", name));
    match value.strip_prefix('{').and_then(|v| v.strip_suffix('}')) {
        Some(target) => resolve(raw, target, depth + 1),
        None => value.clone(),
    }
}

fn parse_hex(name: &str, value: &str) -> [u8; 4] {
    let hex = value.strip_prefix('#').unwrap_or_else(|| fail(&format!("{name} is not a hex colour: {value}")));
    let byte =
        |i: usize| u8::from_str_radix(&hex[i..i + 2], 16).unwrap_or_else(|_| fail(&format!("{name}: bad hex {value}")));
    match hex.len() {
        6 => [byte(0), byte(2), byte(4), 255],
        8 => [byte(0), byte(2), byte(4), byte(6)],
        _ => fail(&format!("{name}: expected #rrggbb or #rrggbbaa, found {value}")),
    }
}

fn px(name: &str, value: &str) -> f32 {
    let number = value.strip_suffix("px").unwrap_or(value);
    number.parse().unwrap_or_else(|_| fail(&format!("{name}: expected a px length, found {value}")))
}

fn field(name: &str) -> String {
    name.replace('-', "_")
}

fn struct_def(out: &mut String, ty: &str, names: &[&str], field_ty: &str) {
    writeln!(out, "#[derive(Clone, Debug)]\npub struct {ty} {{").unwrap();
    for name in names {
        writeln!(out, "    pub {}: {field_ty},", field(name)).unwrap();
    }
    out.push_str("}\n\n");
}
